# Base SonarQube configuration for City of Helsinki Backend projects
sonar.organization=city-of-helsinki
sonar.python.coverage.reportPaths=coverage.xml
sonar.test.inclusions=**/tests/**/*
sonar.exclusions=**/tests/**/*
