group:
  # backend, pip
  - repos: |
      City-of-Helsinki/django-helsinki-notification
      City-of-Helsinki/django-helusers
      City-of-Helsinki/django-munigeo
      City-of-Helsinki/django-orghierarchy
      City-of-Helsinki/django-auditlog-extra
      City-of-Helsinki/django-ilmoitin
      City-of-Helsinki/django-logger-extra
      City-of-Helsinki/example-backend-profile
      City-of-Helsinki/helsinki-profile-gdpr-api
      City-of-Helsinki/kerrokantasi
    files:
      - source: sync/.commitlintrc.mjs
        dest: .commitlintrc.mjs
      - source: sync/.github/dependabot-pip.yml
        dest: .github/dependabot.yml
      - source: sync/CODEOWNERS-ratkaisutoimiston-backend
        dest: CODEOWNERS

  # frontend, npm
  - repos: |
      City-of-Helsinki/example-ui-profile
      City-of-Helsinki/hds-analytics
      City-of-Helsinki/react-helsinki-notification-manager
    files:
      - source: sync/.commitlintrc.mjs
        dest: .commitlintrc.mjs
      - source: sync/.github/dependabot-npm.yml
        dest: .github/dependabot.yml
      - source: sync/CODEOWNERS-ratkaisutoimiston-frontend
        dest: CODEOWNERS

  # sync helper prompts
  - repos: |
      City-of-Helsinki/kerrokantasi
      City-of-Helsinki/linkedevents
    files:
      - source: sync/.github/prompts/
        dest: .github/prompts/
