name: Common CI for Nodes
on:
  workflow_call:
    inputs:
      # Required parameters
      node-version:
        description: 'node version to use'
        required: true
        type: string
  workflow_dispatch:

jobs:
  commitlint:
    name: Check commit messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run commitlint
        uses: wagoid/commitlint-github-action@3d28780bbf0365e29b144e272b2121204d5be5f3  # v6.1.2

  build:
    name: Lint and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        # Prefer offline to check cache before downloading
        run: yarn --prefer-offline
      - name: Lint application
        run: yarn lint
      - name: Build application
        run: yarn build

  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'
    - name: Install dependencies
      # Prefer offline to check cache before downloading
      run: yarn --prefer-offline
    - name: Run tests
      run: yarn test:coverage
      env:
        CI: true

    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v5.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        